apiVersion: v1
kind: ServiceAccount
metadata:
  name: mothership
  namespace: mothership
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mothership
  namespace: mothership
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mothership
  namespace: mothership
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mothership
subjects:
  - kind: ServiceAccount
    name: mothership
    namespace: mothership
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mothership
rules:
  - apiGroups:
      - "certificates.k8s.io"
    resources:
      - certificatesigningrequests
    verbs:
      - create
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mothership
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mothership
subjects:
  - kind: ServiceAccount
    name: mothership
    namespace: mothership