apiVersion: apps/v1
kind: Deployment
metadata:
  name: mothership-ui-deployment
  namespace: mothership
spec:
  selector:
    matchLabels:
      app: mothership-ui
  template:
    metadata:
      labels:
        app: mothership-ui
    spec:
      serviceAccountName: mothership
      containers:
        - name: mothership-ui
          image: ghcr.io/mstg/mship_ui@sha256:4b80a62cd4d69911d7e4de21a474d9271ee3c41e2e994b4fb2f42e60cecd4880
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_URI
              value: http://mothership-api-service:6678
            - name: ADMIN_API_URI
              value: http://mothership-admin-api-service:6688
            - name: SELF
              value: "https://imports.openela.org"
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: gh
                  key: client_id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gh
                  key: client_secret
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: csrf
                  key: secret
            - name: REDIS_HOST
              value: redis-master.default.svc.cluster.local
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: password
          resources:
            requests:
              memory: "128Mi"
              cpu: "300m"
          ports:
            - name: http
              containerPort: 9111
---
apiVersion: v1
kind: Service
metadata:
  name: mothership-ui-service
  namespace: mothership
spec:
  selector:
    app: mothership-ui
  ports:
    - name: http
      protocol: TCP
      port: 9111
      targetPort: 9111
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mothership-ui-ingress
  namespace: mothership
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "308"
spec:
  ingressClassName: kong
  tls:
    - hosts:
        - imports.openela.org
      secretName: mothership-tls
  rules:
    - host: imports.openela.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mothership-ui-service
                port:
                  number: 9111