# Copyright 2024 The Mothership Authors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.ingress.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mothership
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
spec:
  secretName: mothership-tls
  issuerRef:
    kind: ClusterIssuer
    name: goog-prod
  dnsNames:
    - {{ .Values.ingress.host }}
{{- end }}