apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
type: Opaque
data:
  uri: {{ required "database.uri" .Values.database.uri | b64enc }}
---
{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ required "oidc.client_secret" .Values.oidc.client_secret | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: csrf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ randAlphaNum 32 | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
type: Opaque
data:
  private_key: {{ required "github.private_key" .Values.github.private_key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
type: Opaque
data:
  access_key: {{ required "storage.access_key" .Values.storage.access_key | b64enc }}
  secret_key: {{ required "storage.secret_key" .Values.storage.secret_key | b64enc }}