# Copyright 2024 The Mothership Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: mothership
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mothership
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mothership
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mothership
subjects:
  - kind: ServiceAccount
    name: mothership
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mothership
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "certificates.k8s.io"
    resources:
      - certificatesigningrequests
    verbs:
      - create
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mothership
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mothership
subjects:
  - kind: ServiceAccount
    name: mothership
    namespace: {{ .Release.Namespace }}