{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mothership-ui-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: mothership-ui
  template:
    metadata:
      labels:
        app: mothership-ui
    spec:
      serviceAccountName: mothership
      containers:
        - name: mothership-ui
          image: "{{ .Values.image.repository }}/ui:{{ .Values.image.tag }}"
          env:
            - name: MOTHERSHIP_PUBLIC_API
              value: mothership-api-service:6677
            - name: MOTHERSHIP_ADMIN_API
              value: mothership-admin-api-service:6687
            - name: INSTANCE_NAME
              value: "OpenELA Imports"
            - name: SELF
              value: "https://{{ .Values.ingress.host }}"
            - name: REQUIRED_OIDC_GROUP
              value: {{ .Values.oidc.required_group | quote }}
            - name: OIDC_ISSUER
              value: {{ .Values.oidc.issuer | quote }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.oidc.client_id | quote }}
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oidc
                  key: secret
            - name: CSRF_SECRET
              valueFrom:
                secretKeyRef:
                  name: csrf
                  key: secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9111
---
apiVersion: v1
kind: Service
metadata:
  name: mothership-ui-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
spec:
  selector:
    app: mothership-ui
  ports:
    - name: http
      protocol: TCP
      port: 9111
      targetPort: 9111
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mothership-ui-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mothership.labels" . | nindent 4 }}
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "308"
spec:
  ingressClassName: kong
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: mothership-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mothership-ui-service
                port:
                  number: 9111
{{- end }}
{{- end }}