# Default values for mothership.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

database:
  uri: postgres://postgres:password@localhost:5432/postgres # uri is the connection string for the database.

ui:
  enabled: true # enables/disables the UI deployment.

admin:
  enabled: true # enables/disables the admin API deployment.

oidc:
  required_group: "releng" # required_group is the group required for access to the application.
  issuer: "https://id.openela.org/realms/openela" # issuer is the URL of the OpenID Connect provider.
  client_id: "mothership" # client_id is the client id used to authenticate with the OpenID Connect provider.
  client_secret: "" # client_secret is the client secret used to authenticate with the OpenID Connect provider.

github:
  public: "false" # public determines whether repositories are public or private.
  organization: "openela-main" # organization is the GitHub organization used for the application.
  app_id: "416803" # app_id is the GitHub App ID used for the application.
  private_key: "" # private_key is the private key used to authenticate with the GitHub App.

storage:
  endpoint: https://ax8edlmsvvfp.compat.objectstorage.us-phoenix-1.oraclecloud.com # endpoint is the endpoint for the storage service.
  access_key: "" # access_key is the access key used to authenticate with the storage service
  secret_key: "" # secret_key is the secret key used to authenticate with the storage service
  region: us-phoenix-1 # region is the region used for the storage service.
  connection_string: s3://mship-srpm1 # connection_string is the connection string used to access the storage service.
  path_style: "true" # path_style determines whether the storage service uses path style access which includes the bucket name.

bugtracker:
  provider: "github" # provider is the provider used for the bug tracker.
  repository: "openela/issues" # repository is the repository used for the bug tracker.
  use_forge_auth: "true" # use_forge_auth determines whether the bug tracker uses Forge authentication.

temporal:
  address: "temporal-frontend.default.svc.cluster.local:7233" # address is the address used to connect to the Temporal service.
  namespace: "mothership" # namespace is the namespace used for the Temporal service.
  task_queue: "worker" # task_queue is the task queue used for the Temporal service.

image:
  repository: ghcr.io/mstg # repository is a base url and has expectations for the image name to be set off that per application.
  pullPolicy: Always # pullPolicy is set to always since default configuration is "latest".
  tag: "latest" # tag assumes all services are using the same tag.

ingress:
  enabled: false # enabled determines whether the ingress is enabled and if it is then it requires CertManager to be installed.
  host: "imports.openela.org" # host is the host used for the ingress.

worker:
  import_rolling: false # import_rolling determines branch strategy for imports.

# The chart assumes that all containers will use the same resources.
resources:
  requests:
    cpu: "300m" # cpu is set for all containers.
    memory: "128Mi" # memory is set for all containers.
