#!/usr/bin/env bash

# If .local does not exist, create it
if [[ ! -d ".local" ]]; then
  mkdir .local
fi
GOBIN=$(pwd)/.local go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
GOBIN=$(pwd)/.local go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
GOBIN=$(pwd)/.local go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.18.0

PATH="$(pwd)/.local:$PATH" protoc \
  -I. \
  -Ithird_party/googleapis \
  --go_out=. --go_opt=paths=source_relative \
  --go-grpc_out=. --go-grpc_opt=paths=source_relative \
  --grpc-gateway_out=. --grpc-gateway_opt logtostderr=true --grpc-gateway_opt paths=source_relative \
  proto/v1/*.proto \
  proto/admin/v1/*.proto

PATH="$(pwd)/.local:$PATH" protoc \
  -Ithird_party/googleapis \
  --go_out=third_party/googleapis --go_opt=paths=source_relative \
  --go-grpc_out=third_party/googleapis --go-grpc_opt=paths=source_relative \
  --grpc-gateway_out=third_party/googleapis --grpc-gateway_opt logtostderr=true --grpc-gateway_opt paths=source_relative \
  third_party/googleapis/google/longrunning/operations.proto
